### ISSUE TITLE
Pylint

### ISSUE THREAD

**Issue by VaeterchenFrost** [AndyMissed/luck-o-tron#1]
Hi there, looked through your repo after you posted in discord.
Looks very logical and for the most part concise, but there are still some things to improve.
For a start I would recommend https://pypi.org/project/pylint/ that analyzes your code and gives you automated feedback.
Some things in your code for example:

- Standard indentation is usually 4 spaces, (you have 2) making it easier to identify blocks
- Use more vertical space for lines; you have some lines >100 wide
- Look how [Docstrings](https://www.python.org/dev/peps/pep-0257/) are written in python; 
making it more user friendly (than your comments above methods)
- Variable names like a, b, c, d, e, s are not descriptive - it looks like you want to make some choices or a list at that place maybe?
- The module name "L-o-T" has an unusual format, normally python files are named like "snake_case" using lower letters and underscores.

I hope that gives you some hints for further development, otherwise good job 👍

**Comment by AndyMissed** [comment]
Thank you for taking the time to give me some pointers. I will be sure to try out Pylint when I get a chance.

As for the 2 space indent, it's more of a preference for me, but yes, 4 is definitely the standard. But you are right about the 'a, b, c, d, e, s' variable names; I should improve that section of my code, as I left it behind 'as is' throughout my code restructuring.

I will keep all of your advice in mind, and I appreciate your time.

Thanks again!
